### Create a Report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "price": 50000,
  "make": "toyota",
  "model": "corolla",
  "year": 2015,
  "mileage": 10000,
  "lat": 0,
  "lng": 0
}

### Approve report
PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
  "approved": true
}

### Get Estimate
GET http://localhost:3000/reports?make=toyota&model=corolla&year=2015&mileage=10000&lat=0&lng=0